# Generated by Django 4.2.13 on 2024-06-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="progress_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("page", "Page"),
                    ("chapter", "Chapter"),
                    ("part", "Part"),
                    ("episode", "Episode"),
                    ("track", "Track"),
                    ("cycle", "Cycle"),
                    ("timestamp", "Timestamp"),
                    ("percentage", "Percentage"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="progress_value",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["owner", "item", "created_time"],
                name="journal_not_owner_i_7f9460_idx",
            ),
        ),
    ]
