# Generated by Django 3.2.16 on 2023-01-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_auto_20230113_0506"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelflogentry",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
