# Generated by Django 4.2.17 on 2024-12-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_task_type"),
        ("journal", "0003_note_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoufenExporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.task",),
        ),
    ]
