# Generated by Django 4.2.17 on 2025-01-27 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_task_type"),
        ("journal", "0004_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvExporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.task",),
        ),
    ]
