# Generated by Django 4.2.18 on 2025-02-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_steamimporter_alter_task_type'),
        ('journal', '0005_csvexporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdjsonExporter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.task',),
        ),
    ]
