# Generated by Django 3.2.16 on 2023-01-31 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_initial"),
        ("journal", "0008_alter_shelfmember_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="focus_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="focused_comments",
                to="catalog.item",
            ),
        ),
    ]
