# Generated by Django 3.2.18 on 2023-04-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0009_comment_focus_item"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shelfmember",
            index=models.Index(
                fields=["parent_id", "visibility", "created_time"],
                name="journal_she_parent__9da946_idx",
            ),
        ),
    ]
