# Generated by Django 3.2.19 on 2023-06-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_performance"),
        ("journal", "0010_shelfmember_journal_she_parent__9da946_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Memo",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="Comment",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="Comment",
            name="focus_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="focused_comments",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="Review",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="Rating",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="ShelfMember",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="Shelf",
            name="items",
            field=models.ManyToManyField(
                related_name="_journal_shelf_items_+",
                through="journal.ShelfMember",
                to="catalog.Item",
            ),
        ),
        migrations.AlterField(
            model_name="ShelfLogEntry",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="CollectionMember",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="Collection",
            name="items",
            field=models.ManyToManyField(
                related_name="collections",
                through="journal.CollectionMember",
                to="catalog.Item",
            ),
        ),
        migrations.AlterField(
            model_name="TagMember",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
            ),
        ),
        migrations.AlterField(
            model_name="Tag",
            name="items",
            field=models.ManyToManyField(
                through="journal.TagMember", to="catalog.Item"
            ),
        ),
    ]
