# Generated by Django 4.2.3 on 2023-07-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_item_polymorphic_ctype"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("journal", "0011_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="items",
            field=models.ManyToManyField(
                related_name="+", through="journal.ShelfMember", to="catalog.item"
            ),
        ),
    ]
