# Generated by Django 4.2.3 on 2023-07-12 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0012_alter_piece_polymorphic_ctype_alter_shelf_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="focus_item",
        ),
    ]
