# Generated by Django 4.2.3 on 2023-08-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "journal",
            "0014_remove_reply_piece_ptr_remove_reply_reply_to_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piece",
            options={},
        ),
        migrations.AddField(
            model_name="piece",
            name="local",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="piece",
            name="post_id",
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="remote_id",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="remote_id",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="remote_id",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name="piece",
            index=models.Index(
                fields=["post_id"], name="journal_pie_post_id_6a74ff_idx"
            ),
        ),
    ]
