# Generated by Django 4.2.4 on 2023-08-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_apidentity"),
        ("journal", "0014_alter_piece_options_piece_local_piece_post_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="featured_by_users",
        ),
        migrations.AddField(
            model_name="collection",
            name="featured_by",
            field=models.ManyToManyField(
                related_name="featured_collections",
                through="journal.FeaturedCollection",
                to="users.apidentity",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="collectionmember",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="shelflogentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="shelfmember",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="tagmember",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
    ]
