# Generated by Django 4.2.4 on 2023-08-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("journal", "0014_alter_piece_options_piece_local_piece_post_id_and_more"),
        ("journal", "0015_alter_collection_featured_by_users_and_more"),
    ]

    dependencies = [
        (
            "journal",
            "0014_remove_reply_piece_ptr_remove_reply_reply_to_content_and_more",
        ),
        ("users", "0013_init_identity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piece",
            options={},
        ),
        migrations.AddField(
            model_name="piece",
            name="local",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="piece",
            name="post_id",
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="remote_id",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="remote_id",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="remote_id",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name="piece",
            index=models.Index(
                fields=["post_id"], name="journal_pie_post_id_6a74ff_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="collection",
            name="featured_by_users",
        ),
        migrations.AddField(
            model_name="collection",
            name="featured_by",
            field=models.ManyToManyField(
                related_name="featured_collections",
                through="journal.FeaturedCollection",
                to="users.apidentity",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="collectionmember",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="shelflogentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="shelfmember",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
        migrations.AlterField(
            model_name="tagmember",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.apidentity"
            ),
        ),
    ]
