# Generated by Django 4.2.4 on 2023-08-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0016_piecepost_piece_posts_piecepost_unique_piece_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piece",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveIndex(
            model_name="piece",
            name="journal_pie_post_id_6a74ff_idx",
        ),
        migrations.RemoveField(
            model_name="piece",
            name="post_id",
        ),
    ]
