# Generated by Django 4.2.7 on 2023-11-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0019_alter_collection_edited_time_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shelflogentry",
            constraint=models.UniqueConstraint(
                fields=("owner", "item", "timestamp", "shelf_type"),
                name="unique_shelf_log_entry",
            ),
        ),
    ]
