# Generated by Django 4.2.13 on 2024-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0023_debris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="brief",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(default="", max_length=1000, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="shelf_type",
            field=models.CharField(
                choices=[
                    ("wishlist", "WISHLIST"),
                    ("progress", "PROGRESS"),
                    ("complete", "COMPLETE"),
                    ("dropped", "DROPPED"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="shelflogentry",
            name="shelf_type",
            field=models.CharField(
                choices=[
                    ("wishlist", "WISHLIST"),
                    ("progress", "PROGRESS"),
                    ("complete", "COMPLETE"),
                    ("dropped", "DROPPED"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
