# Generated by Django 4.2.13 on 2024-06-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0024_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="pinned",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
