# Generated by Django 3.2.16 on 2023-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="default_no_share",
            field=models.BooleanField(default=False),
        ),
    ]
