# Generated by Django 4.2.13 on 2024-06-16 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_preference_auto_bookmark_cats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="no_anonymous_view",
        ),
    ]
