# Generated by Django 3.2.18 on 2023-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_preference_default_no_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="discover_layout",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
