# Generated by Django 3.2.18 on 2023-04-20 13:31

from django.db import migrations, models

sql = 'ALTER TABLE users_preference ALTER COLUMN "classic_homepage" TYPE SMALLINT USING CASE WHEN classic_homepage THEN 1 ELSE 0 END;'


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_preference_discover_layout"),
    ]

    operations = [
        migrations.RunSQL(sql),
        migrations.AlterField(
            model_name="preference",
            name="classic_homepage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
