# Generated by Django 3.2.19 on 2023-06-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_add_dedicated_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=None,
                null=True,
                max_length=254,
                unique=False,
                verbose_name="email address",
            ),
        ),
        migrations.RunSQL("UPDATE users_user SET email = null;"),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=None,
                null=True,
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
