# Generated by Django 4.2.17 on 2024-12-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_follow_owner_remove_follow_target_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("journal.doufenexporter", "doufen exporter"),
                    ("journal.letterboxdimporter", "letterboxd importer"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE users_task SET type='journal.letterboxdimporter' WHERE type='import.letterboxd'"
        ),
    ]
