# Generated by Django 3.2.19 on 2023-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_unique_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                default=None,
                max_length=254,
                null=True,
                verbose_name="email address pending verification",
            ),
        ),
    ]
