# Generated by Django 4.2.18 on 2025-03-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("journal.baseimporter", "base importer"),
                    ("journal.csvexporter", "csv exporter"),
                    ("journal.csvimporter", "csv importer"),
                    ("journal.doubanimporter", "douban importer"),
                    ("journal.doufenexporter", "doufen exporter"),
                    ("journal.goodreadsimporter", "goodreads importer"),
                    ("journal.letterboxdimporter", "letterboxd importer"),
                    ("journal.ndjsonexporter", "ndjson exporter"),
                    ("journal.ndjsonimporter", "ndjson importer"),
                    ("journal.opmlimporter", "opml importer"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
