# Generated by Django 4.2.3 on 2023-07-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_add_local_mute_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="hidden_categories",
            field=models.JSONField(default=list),
        ),
    ]
