# Generated by Django 4.2.7 on 2023-11-11 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_preference_mastodon_skip_relationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mastodon_last_reachable",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
