# Generated by Django 4.2.8 on 2023-12-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_rename_preference_default_no_share"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["mastodon_site", "mastodon_username"],
                name="users_user_mastodo_bd2db5_idx",
            ),
        ),
    ]
