# Generated by Django 4.2.10 on 2024-04-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                default="en",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
