# Generated by Django 4.2.3 on 2023-07-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("developer", "0002_alter_application_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="redirect_uris",
            field=models.TextField(
                help_text="Allowed URIs list, space separated, at least one URI is required"
            ),
        ),
    ]
