# Generated by Django 4.2.18 on 2025-02-09 02:40

import django_rq
from django.db import migrations

from catalog.common.migrations import fix_20250208


# this is a fix for a bug introduced in 0.10
# safe to be excluded in squashed migration in future
def fix_soft_deleted_edition(apps, schema_editor):
    django_rq.get_queue("mastodon").enqueue(fix_20250208)
    print("(Queued)", end="")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial_0_10"),
    ]

    operations = [
        migrations.RunPython(fix_soft_deleted_edition),
    ]
