# Generated by Django 3.2.16 on 2023-02-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_podcast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastepisode",
            name="item_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="catalog.item",
            ),
        ),
    ]
