# Generated by Django 3.2.19 on 2023-06-19 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_performance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalItem",
        ),
    ]
