# Generated by Django 4.2.7 on 2023-11-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon", "0002_add_api_domain_server_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastodonapplication",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mastodonapplication",
            name="last_reachable_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
