# Generated by Django 4.2.9 on 2024-01-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon", "0003_mastodonapplication_reachable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastodonapplication",
            name="api_domain",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="domain for api call"
            ),
        ),
        migrations.AlterField(
            model_name="mastodonapplication",
            name="app_id",
            field=models.CharField(max_length=200, verbose_name="in-site app id"),
        ),
        migrations.AlterField(
            model_name="mastodonapplication",
            name="client_id",
            field=models.CharField(max_length=200, verbose_name="client id"),
        ),
        migrations.AlterField(
            model_name="mastodonapplication",
            name="client_secret",
            field=models.CharField(max_length=200, verbose_name="client secret"),
        ),
        migrations.AlterField(
            model_name="mastodonapplication",
            name="domain_name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="site domain name"
            ),
        ),
        migrations.AlterField(
            model_name="mastodonapplication",
            name="server_version",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="type and verion"
            ),
        ),
    ]
