# Generated by Django 3.2.16 on 2023-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localactivity",
            name="template",
            field=models.CharField(
                choices=[
                    ("mark_item", "Markitem"),
                    ("review_item", "Reviewitem"),
                    ("create_collection", "Createcollection"),
                    ("like_collection", "Likecollection"),
                    ("feature_collection", "Featurecollection"),
                ],
                max_length=50,
            ),
        ),
    ]
