# Generated by Django 4.2.3 on 2023-07-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_alter_localactivity_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localactivity",
            name="template",
            field=models.CharField(
                choices=[
                    ("mark_item", "Markitem"),
                    ("review_item", "Reviewitem"),
                    ("create_collection", "Createcollection"),
                    ("like_collection", "Likecollection"),
                    ("feature_collection", "Featurecollection"),
                    ("comment_child_item", "Commentchilditem"),
                ],
                max_length=50,
            ),
        ),
    ]
